### ISSUE TITLE
6.0.0: test suite is fau=iling

### ISSUE THREAD

**Issue by kloczek** [sunqm/libcint#105]
Looks like something is wring because two units are failing
<details>

```console
+ cd libcint-6.0.0
+ /usr/bin/ctest --test-dir x86_64-redhat-linux-gnu --output-on-failure --force-new-ctest-process -j48
Internal ctest changing into directory: /home/tkloczko/rpmbuild/BUILD/libcint-6.0.0/x86_64-redhat-linux-gnu
Test project /home/tkloczko/rpmbuild/BUILD/libcint-6.0.0/x86_64-redhat-linux-gnu
    Start 1: cinttest
    Start 2: cint3c2etest
1/2 Test #1: cinttest .........................***Failed    0.02 sec
  File "/home/tkloczko/rpmbuild/BUILD/libcint-6.0.0/testsuite/test_cint.py", line 17
    mode=os.RTLD_GLOBAL|os.RTLD_NOW)
    ^
IndentationError: unexpected indent

2/2 Test #2: cint3c2etest .....................***Failed    0.02 sec
  File "/home/tkloczko/rpmbuild/BUILD/libcint-6.0.0/testsuite/test_3c2e.py", line 16
    _cint = ctypes.CDLL(./libcint.so'),
                        ^
SyntaxError: invalid syntax


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.02 sec

The following tests FAILED:
          1 - cinttest (Failed)
          2 - cint3c2etest (Failed)
Errors while running CTest
```
</details>

**Comment by sunqm** [comment]
Test scripts are fixed in the latest release.

**Comment by kloczek** [comment]
Just tested new version and test suite still fails
```console
+ cd libcint-6.1.1
+ /usr/bin/ctest --test-dir x86_64-redhat-linux-gnu --output-on-failure --force-new-ctest-process -j48 ' '
Internal ctest changing into directory: /home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/x86_64-redhat-linux-gnu
Test project /home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/x86_64-redhat-linux-gnu
    Start 1: cinttest
    Start 2: cint3c2etest
1/2 Test #2: cint3c2etest .....................***Failed    0.14 sec
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/testsuite/test_3c2e.py", line 16, in <module>
    _cint = ctypes.CDLL(os.path.abspath(os.path.join(__file__, '../../build/libcint.so')),
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/build/libcint.so: cannot open shared object file: No such file or directory

2/2 Test #1: cinttest .........................***Failed    0.16 sec
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/testsuite/test_cint.py", line 16, in <module>
    _cint = ctypes.CDLL(os.path.abspath(os.path.join(__file__, '../../build/libcint.so')),
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tkloczko/rpmbuild/BUILD/libcint-6.1.1/build/libcint.so: cannot open shared object file: No such file or directory


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.16 sec

The following tests FAILED:
          1 - cinttest (Failed)
          2 - cint3c2etest (Failed)
Errors while running CTest
```
