### ISSUE TITLE
Test failed - `symbol not found` when running test

### ISSUE THREAD

**Issue by NKUCodingCat** [sunqm/libcint#30]
Hey, I am trying to running this repo on my mac, and I running with brew-installed gcc-9 openblas & openmp, it is compiled normally but I run text and get such errors:

libomp 8.0.0 / gcc 9.1.0 /  openblas 0.3.6_1

```
$ make test ARGS=-V
Running tests...
UpdateCTestConfiguration  from :/Users/cjingtao/Downloads/libcint-3.0.15/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/cjingtao/Downloads/libcint-3.0.15/build/DartConfiguration.tcl
Test project /Users/cjingtao/Downloads/libcint-3.0.15/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: cinttest

1: Test command: /usr/bin/python "/Users/cjingtao/Downloads/libcint-3.0.15/testsuite/test_cint.py"
1: Test timeout computed to be: 10000000
1: pass:  cint1e_ovlp_sph
1: pass:  cint1e_nuc_sph
1: pass:  cint1e_kin_sph
1: pass:  cint1e_ia01p_sph
1: pass:  cint1e_cg_irxp_sph
1: pass:  cint1e_giao_irjxp_sph
1: pass:  cint1e_igkin_sph
1: pass:  cint1e_igovlp_sph
1: pass:  cint1e_ignuc_sph
1: pass:  cint1e_ipovlp_sph
1: pass:  cint1e_ipkin_sph
1: pass:  cint1e_ipnuc_sph
1: pass:  cint1e_iprinv_sph
1: pass:  cint1e_prinvxp_sph
1: pass:  cint1e_z_sph
1: pass:  cint1e_zz_sph
1: pass:  cint1e_r_sph
1: pass:  cint1e_rr_sph
1: pass:  cint1e_r2_sph
1: pass:  cint1e_ovlp
1: pass:  cint1e_nuc
1: pass:  cint1e_gnuc
1: pass:  cint1e_srsr
1: pass:  cint1e_sr
1: pass:  cint1e_srsp
1: pass:  cint1e_spsp
1: pass:  cint1e_sp
1: pass:  cint1e_spspsp
1: pass:  cint1e_spnuc
1: pass:  cint1e_spnucsp
1: pass:  cint1e_srnucsr
1: pass:  cint1e_cg_sa10sa01
1: pass:  cint1e_cg_sa10sp
1: pass:  cint1e_cg_sa10nucsp
1: pass:  cint1e_giao_sa10sa01
1: pass:  cint1e_giao_sa10sp
1: pass:  cint1e_giao_sa10nucsp
1: pass:  cint1e_govlp
1: pass:  cint1e_sa01sp
1: pass:  cint1e_spgsp
1: pass:  cint1e_spgnucsp
1: pass:  cint1e_spgsa01
1: pass:  cint1e_ipovlp
1: pass:  cint1e_ipkin
1: pass:  cint1e_ipnuc
1: pass:  cint1e_iprinv
1: pass:  cint1e_ipspnucsp
1: pass:  cint1e_ipsprinvsp
1: pass:  cint2e_sph
1: pass:  cint2e_ip1_sph
1: pass:  cint2e_ip1_sph
1: pass:  cint2e_p1vxp1_sph
1: pass:  cint2e
1: pass:  cint2e_spsp1
1: * FAIL:  cint2e_spsp1spsp2 . err: 0.186581252142787 / 1391716.87687
1: pass:  cint2e_srsr1
1: * FAIL:  cint2e_srsr1srsr2 . err: 0.1161914421245456 / 860883.628827
1: pass:  cint2e_cg_sa10sp1
1: pass:  cint2e_cg_sa10sp1spsp2
1: pass:  cint2e_giao_sa10sp1
1: * FAIL:  cint2e_giao_sa10sp1spsp2 . err: 0.1128864532802254 / 918284.946469
1: pass:  cint2e_g1
1: pass:  cint2e_spgsp1
1: pass:  cint2e_g1spsp2
1: pass:  cint2e_spgsp1spsp2
1: pass:  cint2e_ip1
1: pass:  cint2e_ipspsp1
1: pass:  cint2e_ip1spsp2
1: pass:  cint2e_ipspsp1spsp2
1: pass:  cint2e_spsp1 / cint2e
1: pass:  cint2e_spsp1spsp2 / cint2e
1: pass:  cint2e_spsp1spsp2 / cint2e_spsp1
1: pass:  cint2e_spgsp1 / cint2e_g1
1: pass:  cint2e_g1spsp2 / cint2e_g1
1: pass:  cint2e_spgsp1spsp2 / cint2e_g1
1: pass:  cint2e_ipspsp1 / cint2e_ip1
1: pass:  cint2e_ip1spsp2 / cint2e_ip1
1: pass:  cint2e_ipspsp1spsp2 / cint2e_ip1
1/2 Test #1: cinttest .........................   Passed   90.12 sec
test 2
    Start 2: cint3c2etest

2: Test command: /usr/bin/python "/Users/cjingtao/Downloads/libcint-3.0.15/testsuite/test_3c2e.py"
2: Test timeout computed to be: 10000000
2: pass:  cint3c2e_sph
2: pass:  cint3c2e_ip1_sph
2: pass:  cint3c2e_ip2_sph
2: Traceback (most recent call last):
2:   File "/Users/cjingtao/Downloads/libcint-3.0.15/testsuite/test_3c2e.py", line 312, in <module>
2:     test_int3c2e_spinor(*f)
2:   File "/Users/cjingtao/Downloads/libcint-3.0.15/testsuite/test_3c2e.py", line 233, in test_int3c2e_spinor
2:     intor = getattr(_cint, name)
2:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
2:     func = self.__getitem__(name)
2:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
2:     func = self._FuncPtr((name_or_ordinal, self))
2: AttributeError: dlsym(0x7f98b1f38670, cint3c2e_spinor): symbol not found
2/2 Test #2: cint3c2etest .....................***Failed    0.23 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =  90.36 sec

The following tests FAILED:
          2 - cint3c2etest (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Is there any advice to work around it?

**Comment by sunqm** [comment]
Fails in the first test are due to the numerical round-off error in the high order integral derivatives. When quadmath library is available in the system, a smaller error can be expected. Unless dealing with high order derivatives of high angular momentum basis, typically,  you don't have to worry about the numerical error.

The second test was developed on Linux. Mac OS may not be well supported.

**Comment by NKUCodingCat** [comment]
Thanks, I will try it on linux

**Comment by boegel** [comment]
@sunqm I'm observing the exact same problem with the tests as reported by @NKUCodingCat, that is:

* the 3 same failing tests:
  ```
  ...
  pass:  cint2e_spsp1
  * FAIL:  cint2e_spsp1spsp2 . err: 0.186581252142787 / 1391716.87687
  pass:  cint2e_srsr1
  * FAIL:  cint2e_srsr1srsr2 . err: 0.1161914421245456 / 860883.628827
  pass:  cint2e_cg_sa10sp1
  pass:  cint2e_cg_sa10sp1spsp2
  pass:  cint2e_giao_sa10sp1
  * FAIL:  cint2e_giao_sa10sp1spsp2 . err: 0.1128864532802254 / 918284.946469
  pass:  cint2e_g1
  ...
  ```

* the missing symbol for `cint3c2etest`:
```
  2/2 Test: cint3c2etest
  Command: "/software/Python/2.7.15-GCCcore-8.2.0/bin/python" "/tmp/libcint/3.0.18/foss-2019a/libcint-3.0.18/testsuite/test_3c2e.py"
  Directory: /tmp/libcint/3.0.18/foss-2019a/easybuild_obj
  "cint3c2etest" start time: Aug 11 10:07 CEST
  Output:
  ----------------------------------------------------------
  pass:  cint3c2e_sph
  pass:  cint3c2e_ip1_sph
  pass:  cint3c2e_ip2_sph
  Traceback (most recent call last):
    File "/tmp/libcint/3.0.18/foss-2019a/libcint-3.0.18/testsuite/test_3c2e.py", line 312, in <module>
      test_int3c2e_spinor(*f)
    File "/tmp/libcint/3.0.18/foss-2019a/libcint-3.0.18/testsuite/test_3c2e.py", line 233, in test_int3c2e_spinor
      intor = getattr(_cint, name)
    File "/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
      func = self.__getitem__(name)
    File "/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
      func = self._FuncPtr((name_or_ordinal, self))
  AttributeError: /tmp//libcint/3.0.18/foss-2019a/easybuild_obj/libcint.so: undefined symbol: cint3c2e_spinor
  <end of output>
  Test time =   0.19 sec
  ----------------------------------------------------------
  Test Failed.
  ```

I'm seeing this on Linux (CentOS 7.6.1810) though, and *with* quadmath available, using two different compiler toolchains:

* GCC 8.2.0 (+ binutils 2.31.1), OpenBLAS 0.3.5
* Intel compilers + Intel MKL 2019 update 1

I'm also seeing these same issues on different processor architectures (Intel Sandy Bridge, Haswell & Skylake).
