### ISSUE TITLE
cint3c2etest fails

### ISSUE THREAD

**Issue by jjgoings** [sunqm/libcint#8]
Seems to compile fine, but `make test` fails on the second test set. Not sure how to make test more verbose, so it's unclear to me what may be wrong. Let me know and I can give more information.

```
Running tests...
Test project /home/jjgoings/libcint/build
    Start 1: cinttest
1/2 Test #1: cinttest .........................   Passed   95.57 sec
    Start 2: cint3c2etest
2/2 Test #2: cint3c2etest .....................***Failed    0.16 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =  95.73 sec

The following tests FAILED:
	  2 - cint3c2etest (Failed)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8
```

**Comment by matt-chan** [comment]
You can use `make test ARGS=-V` to get more verbosity.

Do you have pyscf installed and on your PYTHONPATH? That's my guess why it's failing.

**Comment by jjgoings** [comment]
Thanks for the quick reply! 

No, actually I have not installed `pyscf`. I think this is why the test fails, since I see the import error. It might be nice to mention the `pyscf` requirement in the `README`. It's also interesting that test 1 shows some failures but finishes with a `PASS`.

```
Running tests...
UpdateCTestConfiguration  from :/home/jjgoings/libcint/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jjgoings/libcint/build/DartConfiguration.tcl
Test project /home/jjgoings/libcint/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: cinttest

1: Test command: /usr/bin/python "/home/jjgoings/libcint/testsuite/test_cint.py"
1: Test timeout computed to be: 9.99988e+06
1: pass:  cint1e_ovlp_sph
1: pass:  cint1e_nuc_sph
1: pass:  cint1e_kin_sph
1: pass:  cint1e_ia01p_sph
1: pass:  cint1e_cg_irxp_sph
1: pass:  cint1e_giao_irjxp_sph
1: pass:  cint1e_igkin_sph
1: pass:  cint1e_igovlp_sph
1: pass:  cint1e_ignuc_sph
1: pass:  cint1e_ipovlp_sph
1: pass:  cint1e_ipkin_sph
1: pass:  cint1e_ipnuc_sph
1: pass:  cint1e_iprinv_sph
1: pass:  cint1e_prinvxp_sph
1: pass:  cint1e_z_sph
1: pass:  cint1e_zz_sph
1: pass:  cint1e_r_sph
1: pass:  cint1e_rr_sph
1: pass:  cint1e_r2_sph
1: pass:  cint1e_ovlp
1: pass:  cint1e_nuc
1: pass:  cint1e_gnuc
1: pass:  cint1e_srsr
1: pass:  cint1e_sr
1: pass:  cint1e_srsp
1: pass:  cint1e_spsp
1: pass:  cint1e_sp
1: pass:  cint1e_spspsp
1: pass:  cint1e_spnuc
1: pass:  cint1e_spnucsp
1: pass:  cint1e_srnucsr
1: pass:  cint1e_cg_sa10sa01
1: pass:  cint1e_cg_sa10sp
1: pass:  cint1e_cg_sa10nucsp
1: pass:  cint1e_giao_sa10sa01
1: pass:  cint1e_giao_sa10sp
1: pass:  cint1e_giao_sa10nucsp
1: pass:  cint1e_govlp
1: pass:  cint1e_sa01sp
1: pass:  cint1e_spgsp
1: pass:  cint1e_spgnucsp
1: pass:  cint1e_spgsa01
1: pass:  cint1e_ipovlp
1: pass:  cint1e_ipkin
1: pass:  cint1e_ipnuc
1: pass:  cint1e_iprinv
1: pass:  cint1e_ipspnucsp
1: pass:  cint1e_ipsprinvsp
1: * FAIL:  cint2e_sph . err: 5.255133146420121e-07 / 56243.8832877
1: * FAIL:  cint2e_ig1_sph . err: 3.765482688322663e-06 / 8101.0873344
1: * FAIL:  cint2e_ip1_sph . err: 1.087461714632809e-05 / 115489.864387
1: * FAIL:  cint2e_p1vxp1_sph . err: 6.967771332710981e-05 / 89014.8816974
1: * FAIL:  cint2e . err: 3.116438165307045e-07 / 37737.1136571
1: * FAIL:  cint2e_spsp1 . err: 0.0001092366874217987 / 221528.476467
1: * FAIL:  cint2e_spsp1spsp2 . err: 0.006990435300394893 / 1391716.87687
1: * FAIL:  cint2e_srsr1 . err: 4.582744440995157e-05 / 178572.739831
1: * FAIL:  cint2e_srsr1srsr2 . err: 0.001948476652614772 / 860883.628827
1: * FAIL:  cint2e_cg_sa10sp1 . err: 7.509652641601861e-05 / 241519.214365
1: * FAIL:  cint2e_cg_sa10sp1spsp2 . err: 0.004072270588949323 / 1419443.46977
1: * FAIL:  cint2e_giao_sa10sp1 . err: 5.367101402953267e-05 / 153861.920808
1: * FAIL:  cint2e_giao_sa10sp1spsp2 . err: 0.004195312969386578 / 918284.946469
1: * FAIL:  cint2e_g1 . err: 1.482840616517933e-06 / 3755.25159189
1: * FAIL:  cint2e_spgsp1 . err: 4.500812065089121e-05 / 16626.9910379
1: * FAIL:  cint2e_g1spsp2 . err: 0.0004120030207559466 / 22186.5665483
1: * FAIL:  cint2e_spgsp1spsp2 . err: 0.003142444431432523 / 107110.234053
1: * FAIL:  cint2e_ip1 . err: 3.969522367697209e-06 / 34912.8543381
1: * FAIL:  cint2e_ipspsp1 . err: 0.0009000948339235038 / 221092.555604
1: * FAIL:  cint2e_ip1spsp2 . err: 0.0009450505604036152 / 212447.102936
1: * FAIL:  cint2e_ipspsp1spsp2 . err: 0.01673972280696034 / 1443972.93656
1: pass:  cint2e_spsp1 / cint2e
1: pass:  cint2e_spsp1spsp2 / cint2e
1: pass:  cint2e_spsp1spsp2 / cint2e_spsp1
1: pass:  cint2e_spgsp1 / cint2e_g1
1: pass:  cint2e_g1spsp2 / cint2e_g1
1: pass:  cint2e_spgsp1spsp2 / cint2e_g1
1: pass:  cint2e_ipspsp1 / cint2e_ip1
1: pass:  cint2e_ip1spsp2 / cint2e_ip1
1: pass:  cint2e_ipspsp1spsp2 / cint2e_ip1
1: * FAIL:  3 3 5.64582721316e-13
1: * FAIL:  7 7 7.53562844163e-14
1/2 Test #1: cinttest .........................   Passed   96.01 sec
test 2
    Start 2: cint3c2etest

2: Test command: /usr/bin/python "/home/jjgoings/libcint/testsuite/test_3c2e.py"
2: Test timeout computed to be: 9.99988e+06
2: * FAIL:  cint3c2e_sph . err: 1.300577423535287e-10 / 1586.35079743
2: * FAIL:  cint3c2e_ip1_sph . err: 6.803020369261503e-10 / 2242.05224927
2: * FAIL:  cint3c2e_ip2_sph . err: 5.302354111336172e-10 / 1970.98248386
2: Traceback (most recent call last):
2:   File "/home/jjgoings/libcint/testsuite/test_3c2e.py", line 300, in <module>
2:     test_int3c2e_spinor(*f)
2:   File "/home/jjgoings/libcint/testsuite/test_3c2e.py", line 244, in test_int3c2e_spinor
2:     zmat = sf2spinor(opref[:,:,:,0], i, j, bas)
2:   File "/home/jjgoings/libcint/testsuite/test_3c2e.py", line 203, in sf2spinor
2:     import pyscf.symm.cg
2: ImportError: No module named pyscf.symm.cg
2/2 Test #2: cint3c2etest .....................***Failed    0.16 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =  96.17 sec

The following tests FAILED:
	  2 - cint3c2etest (Failed)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8
```
