### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by susilehtola** [sunqm/libcint#98]
The distutils package [was deprecated in Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) and is removed in Python 3.12.

Because of this, the tests of libcint fail in Fedora rawhide, which has Python 3.12
```
+ make -C x86_64-redhat-linux-gnu test ARGS=-V
make: Entering directory '/builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu'
Running tests...
UpdateCTestConfiguration  from :/builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu/DartConfiguration.tcl
UpdateCTestConfiguration  from :/builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu/DartConfiguration.tcl
Test project /builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: cinttest
1: Test command: /usr/bin/python3.12 "/builddir/build/BUILD/libcint-5.4.0/testsuite/test_cint.py" "--quick"
1: Working Directory: /builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu
1: Test timeout computed to be: 10000000
1: Traceback (most recent call last):
1:   File "/builddir/build/BUILD/libcint-5.4.0/testsuite/test_cint.py", line 16, in <module>
1:     _cint = numpy.ctypeslib.load_library('libcint','.')
1:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1:   File "/usr/lib64/python3.12/site-packages/numpy/ctypeslib.py", line 137, in load_library
1:     from numpy.distutils.misc_util import get_shared_lib_extension
1:   File "/usr/lib64/python3.12/site-packages/numpy/distutils/__init__.py", line 26, in <module>
1:     from . import ccompiler
1:   File "/usr/lib64/python3.12/site-packages/numpy/distutils/ccompiler.py", line 8, in <module>
1:     from distutils import ccompiler
1: ModuleNotFoundError: No module named 'distutils'
1/2 Test #1: cinttest .........................***Failed    0.16 sec
test 2
    Start 2: cint3c2etest
2: Test command: /usr/bin/python3.12 "/builddir/build/BUILD/libcint-5.4.0/testsuite/test_3c2e.py" "--quick"
2: Working Directory: /builddir/build/BUILD/libcint-5.4.0/x86_64-redhat-linux-gnu
2: Test timeout computed to be: 10000000
2: Traceback (most recent call last):
2:   File "/builddir/build/BUILD/libcint-5.4.0/testsuite/test_3c2e.py", line 16, in <module>
2:     _cint = numpy.ctypeslib.load_library('libcint', '.')
2:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2:   File "/usr/lib64/python3.12/site-packages/numpy/ctypeslib.py", line 137, in load_library
2:     from numpy.distutils.misc_util import get_shared_lib_extension
2:   File "/usr/lib64/python3.12/site-packages/numpy/distutils/__init__.py", line 26, in <module>
2:     from . import ccompiler
2:   File "/usr/lib64/python3.12/site-packages/numpy/distutils/ccompiler.py", line 8, in <module>
2:     from distutils import ccompiler
2: ModuleNotFoundError: No module named 'distutils'
2/2 Test #2: cint3c2etest .....................***Failed    0.15 sec
0% tests passed, 2 tests failed out of 2
Total Test time (real) =   0.31 sec
The following tests FAILED:
	  1 - cinttest (Failed)
	  2 - cint3c2etest (Failed)
Errors while running CTest
```

**Comment by susilehtola** [comment]
This has now been fixed in numpy.
